version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python manage.py runserver 0.0.0.0:8000'
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - main

  db:
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - pg-data:/var/lib/mysql
    ports:
      - "5437:5432"
    networks:
      - main

volumes:
  pg-data:

networks:
  main: