version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'bash scripts/backend_entrypoint.sh'
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - main

  db:
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5437:5432"
    networks:
      - main

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/app
    command: 'python -u consumer.py'
    depends_on:
      - db
    restart: always
    networks:
      - main

  rabbit:
    hostname: rabbit
    image: rabbitmq:3.10.0-rc.3-management
    env_file: .env
    ports:
      - "5675:5672" # we forward this port because it's useful for debugging
      - "15675:15672" # here, we can access rabbitmq management plugin
    networks:
      - main


volumes:
  pg-data:

networks:
  main: